import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.io.PrintWriter;

public class TuitionWaiverFormServlet extends HttpServlet{
	
	public void doPost(HttpServletRequest request, HttpServletResponse response) throws IOException{
		
		response.setContentType("text/html");
		PrintWriter out = response.getWriter();
		
		out.println("<html>");
		out.println("<body style=\"border: 1px solid black; padding:1rem 3rem; width:80%; margin-left:5rem\">");
		out.println("<div style=\"display:flex; justify-content: space-between;\">");
		out.println("<div>");
		out.println("<h1 style=\"color:red;\">Northeastern University</h1>");
		out.println("<h2>Human Resources</h2>");
		out.println("</div>");
		out.println("<h1>Tuition Waiver Form</h1>");
		out.println("</div>");
		
		out.println("<div style=\"border: 1px solid black; padding:0.1rem 0.5rem\">");
		out.println("<p>This form is used by part-time faculty, part-time staff, retirees, their spouses or domestic partners and their dependents.  All full-time faculty and staff should use the online Tuition Waiver Form found on myNEU.  Before completing this form, please refer to the Tuition Waiver Program Guidelines.Be sure to include a Dependent Certification Form alongwith the submission of this form for any dependent children. </p>");
		out.println("</div>");
		out.println("<h2 style=\"color:red;\">Section 1</h2>");
		out.println("<label for=\"aterm\">Academic Term: </label>");
		out.println("<input type=\"text\" name=\"aterm\" value=\"" +request.getParameter("aterm")+ "\" style=\"border:none; border-bottom:1px solid black; outline:none\">");
		out.println("<label for=\"ayear\">Academic Year: </label>");
		out.println("<input type=\"text\" name=\"ayear\" value=\"" +request.getParameter("ayear")+ "\"style=\"border:none; border-bottom:1px solid black; outline:none\">");
		out.println("<label for=\"empstatus\">Employee Status: </label>");
		out.println("<input type=\"radio\" value=\"" +request.getParameter("empstatus")+ "\" name=\"empstatus\">P/T Staff"); 
		out.println("<p style=\"margin-top:-0.2rem\">(Fall, Winter, Spring,  or Summer)* </p>");
		out.println("<p>*Terms with multiple sessions are considered one academic term for tuition waiver purposes e.g., summer sessions I andII are considered one academic term.</p>");
		
		out.println("<h2 style=\"color:red;\">Section 2</h2>");
		out.println("<div>");
		out.println("<div style=\"display: flex;justify-content: space-between\">");
		out.println("<input type=\"text\" name=\"studentName\" value=\"" +request.getParameter("studentName")+ "\"style=\"border:none; border-bottom:1px solid black; width:30%; outline:none\">");
		out.println("<input type=\"text\" name=\"relationship\" value=\"" +request.getParameter("relationship")+ "\"style=\"border:none; border-bottom:1px solid black; width:30%; outline:none\">");
		out.println("<input type=\"text\" name=\"nuid\" value=\"" +request.getParameter("nuid")+ "\"style=\"border:none; border-bottom:1px solid black; width:30%; outline:none\">");
		out.println("</div>");
		out.println("<div style=\"display: flex;justify-content: space-between\">");
		out.println("<label for=\"studentName\">Student's Name</label>");
		out.println("<label for=\"relationship\">Relationship to Employee</label>");
		out.println("<label for=\"nuid\">Student's NUID</label>");
		out.println("</div>");
		out.println("</div>");
		out.println("<br>");
		out.println("<div>");
		out.println("<div style=\"display: flex;justify-content: space-between\">");
		out.println("<input type=\"text\" name=\"employeeName\" value=\"" +request.getParameter("employeeName")+ "\"style=\"border:none; border-bottom:1px solid black; width:65%; outline:none\">");
		out.println("<input type=\"text\" name=\"empnuid\" value=\"" +request.getParameter("empnuid")+ "\"style=\"border:none; border-bottom:1px solid black; width:30%; outline:none\">");
		out.println("</div>");
		out.println("<div style=\"display: flex;justify-content: space-between\">");
		out.println("<label for=\"employeeName\">Employee's Name (if different from Student's)</label>");
		out.println("<label for=\"empnuid\">Employee's NUID</label>");
		out.println("</div> </div>");
		out.println("<br>");
		out.println("<div>");
		out.println("<div style=\"display: flex;justify-content: space-between\">");
		out.println("<input type=\"text\" name=\"department\" value=\"" +request.getParameter("department")+ "\"style=\"border:none; border-bottom:1px solid black; outline:none\">");
		out.println("<input type=\"text\" name=\"camplocation\" value=\"" +request.getParameter("camplocation")+ "\"style=\"border:none; border-bottom:1px solid black; outline:none\">");
		out.println("<input type=\"text\" name=\"phnumber\" value=\"" +request.getParameter("phnumber")+ "\"style=\"border:none; border-bottom:1px solid black; outline:none\">");
		out.println("<input type=\"text\" name=\"supname\" value=\"" +request.getParameter("supname")+ "\"style=\"border:none; border-bottom:1px solid black; outline:none\">");
		out.println("</div>");
		out.println("<div style=\"display: flex;justify-content: space-between\">");
		out.println("<label for=\"department\">Department</label>");
		out.println("<label for=\"camplocation\">Campus Location</label>");
		out.println("<label for=\"phnumber\">Phone Number </label>");
		out.println("<label for=\"supname\">Supervisor's Name</label>");
		out.println("</div> </div>");
		
		out.println("<h2 style=\"color:red;\">Section 3 </h2> ");
		out.println("<label for=\"program\"><span><i>Indicate the applicable school or program: </i></span></label>");
		out.println("<input type=\"radio\" value=\"" +request.getParameter("program")+ "\" name=\"program\">" + request.getParameter("program"));
		out.println("<br> <br>");
		out.println("<div style=\"border: 1px solid gray; padding:0rem 0.5rem; background-color:lightgray\">");
		out.println("<p>One course per academic term may be taken one-half hour before the end of your workday. If this applies to you, this form must be signed by your supervisor below and approved by Human Resources Management.</p>");
		out.println("</div> <br>");
		out.println("<div style=\"border: 1px solid gray; padding:0rem 0.5rem; background-color:lightgray\">");
		out.println("<p>Complete the following course information.  If you are an employee taking a job related course, please attach the Job Related Designation Form to this waiver.</p>");
		out.println("</div> <br>");
		out.println("<table>");
		out.println("<thead>");
		out.println("<th><input type=\"text\" style=\"border:none;outline:none\" value=\"Course No.\"></th>");
		out.println("<th><input type=\"text\" style=\"border:none;outline:none\" value=\"Course Name\"></th>");
		out.println("<th><input type=\"text\" style=\"border:none;outline:none\" value=\"Supervisor Signature\"></th>"); 
		out.println("<th><input type=\"text\" style=\"border:none;outline:none\" value=\"Credit Hrs\"></th>"); 
		out.println("<th><input type=\"text\" style=\"border:none;outline:none;margin-left:-3rem\" value=\"Days\"></th>");
		out.println("<th><input type=\"text\" style=\"border:none;outline:none;margin-left:-1rem\" value=\"Time\"></th>");
		out.println("</thead>");
		out.println("<tbody>");
		out.println("<tr>");
			out.println("<td><input type=\"text\" name=\"firstCourse\" value=\"" +request.getParameter("firstCourse")+ "\" style=\"border:none; border-bottom:1px solid black;outline:none;width:50%\"></td>");
			out.println("<td><input type=\"text\" name=\"firstCourseName\" value=\"" +request.getParameter("firstCourseName")+ "\" style=\"border:none; border-bottom:1px solid black;outline:none;width:50%\"></td>");
			out.println("<td><input type=\"text\" name=\"firstSupervisorSignature\" value=\"" +request.getParameter("firstSupervisorSignature")+ "\" style=\"border:none; border-bottom:1px solid black;outline:none;width:50%\"></td>");
			out.println("<td><input type=\"text\" name=\"firstCreditHr\" value=\"" +request.getParameter("firstCreditHr")+ "\" style=\"border:none; border-bottom:1px solid black;outline:none;width:50%\"></td>");
			out.println("<td><input type=\"text\" name=\"firstDays\" value=\"" +request.getParameter("firstDays")+ "\" style=\"border:none; border-bottom:1px solid black;outline:none;width:80%;margin-left:-3rem\"></td>");
			out.println("<td><input type=\"text\" name=\"firstTime\" value=\"" +request.getParameter("firstTime")+ "\" style=\"border:none; border-bottom:1px solid black;outline:none;width:50%;margin-left:-3rem\"></td>");
			out.println("<td>a.m./p.m.</td>");
		out.println("</tr>");
		out.println("<tr>");
			out.println("<td><input type=\"text\" name=\"secondCourse\" value=\"" +request.getParameter("secondCourse")+ "\" style=\"border:none; border-bottom:1px solid black;outline:none;width:50%\"></td>");
			out.println("<td><input type=\"text\" name=\"secondCourseName\" value=\"" +request.getParameter("secondCourseName")+ "\" style=\"border:none; border-bottom:1px solid black;outline:none;width:50%\"></td>");
			out.println("<td><input type=\"text\" name=\"secondSupervisorSignature\" value=\"" +request.getParameter("secondSupervisorSignature")+ "\" style=\"border:none; border-bottom:1px solid black;outline:none;width:50%\"></td>");
			out.println("<td><input type=\"text\" name=\"secondCreditHr\" value=\"" +request.getParameter("secondCreditHr")+ "\" style=\"border:none; border-bottom:1px solid black;outline:none;width:50%\"></td>");
			out.println("<td><input type=\"text\" name=\"secondDays\" value=\"" +request.getParameter("secondDays")+ "\" style=\"border:none; border-bottom:1px solid black;outline:none;width:80%;margin-left:-3rem\"></td>");
			out.println("<td><input type=\"text\" name=\"secondTime\" value=\"" +request.getParameter("secondTime")+ "\" style=\"border:none; border-bottom:1px solid black;outline:none;width:50%;margin-left:-3rem\"></td>");
			out.println("<td>a.m./p.m.</td>");
		out.println("</tr>");
		out.println("<tr>");
			out.println("<td><input type=\"text\" name=\"thirdCourse\" value=\"" +request.getParameter("thirdCourse")+ "\" style=\"border:none; border-bottom:1px solid black;outline:none;width:50%\"></td>");
			out.println("<td><input type=\"text\" name=\"thirdCourseName\" value=\"" +request.getParameter("thirdCourseName")+ "\" style=\"border:none; border-bottom:1px solid black;outline:none;width:50%\"></td>");
			out.println("<td><input type=\"text\" name=\"thirdSupervisorSignature\" value=\"" +request.getParameter("thirdSupervisorSignature")+ "\" style=\"border:none; border-bottom:1px solid black;outline:none;width:50%\"></td>");
			out.println("<td><input type=\"text\" name=\"thirdCreditHr\" value=\"" +request.getParameter("thirdCreditHr")+ "\" style=\"border:none; border-bottom:1px solid black;outline:none;width:50%\"></td>");
			out.println("<td><input type=\"text\" name=\"thirdDays\" value=\"" +request.getParameter("thirdDays")+ "\" style=\"border:none; border-bottom:1px solid black;outline:none;width:80%;margin-left:-3rem\"></td>");
			out.println("<td><input type=\"text\" name=\"thirdTime\" value=\"" +request.getParameter("thirdTime")+ "\" style=\"border:none; border-bottom:1px solid black;outline:none;width:50%;margin-left:-3rem\"></td>");
			out.println("<td>a.m./p.m.</td>");
		out.println("</tr>");
		out.println("</tbody>");
		out.println("</table>");
		
		out.println("<h2 style=\"color:red;\">Section 4</h2>");
		out.println("<h4><strong style=\"font-size:1.1rem\"> In accordance with Northeastern University's Tuition Waiver Program Guidelines, my signature attests that I am currently enrolled in the above courses, or that the student listed above is my spouse, domestic partner or unmarried dependent child or the dependent child of my domestic partner as defined under current IRS tax regulations.  I also certify that I have read the Tuition Waiver Program Guidelines.");
		out.println("</strong></h4>");
		out.println("<div>");
		out.println("<br>");
		out.println("<div style=\"display: flex;justify-content: space-between\">");
		out.println("<input type=\"text\" name=\"empsignature\" value=\"" +request.getParameter("empsignature")+ "\" style=\"border:none; border-bottom:1px solid black;outline:none;width:50%\">");
		out.println("<input type=\"date\" name=\"date1\" value=\"" +request.getParameter("date1")+ "\"style=\"border:none; border-bottom:1px solid black;outline:none;width:20%\">");
		out.println("</div>");
		out.println("<div style=\"display: flex;justify-content: space-between\">");
		out.println("<label for=\"empsignature\">Employee's Signature</label>");
		out.println("<label for=\"date1\">Date </label>");
		out.println("</div> </div>");

		out.println("<h2 style=\"color:red;\">Section 5</h2>");
		out.println("<div>");
		out.println("<div style=\"display: flex;justify-content: space-between\">");
		out.println("<input type=\"text\" name=\"approval\" value=\"" +request.getParameter("approval")+ "\"style=\"border:none; border-bottom:1px solid black;outline:none;width:50%\">");
		out.println("<input type=\"date\" name=\"date2\" value=\"" +request.getParameter("date2")+ "\"style=\"border:none; border-bottom:1px solid black;outline:none;width:20%\">");
		out.println("</div>");
		out.println("<div style=\"display: flex;justify-content: space-between\">");
		out.println("<label for=\"approval\">HRM Approval</label>");
		out.println("<label for=\"date2\">Date</label>");
		out.println("</div> </div>");
		out.println("<br>");
		out.println("<div style=\"border: 1px solid gray; padding:0rem 0.5rem; background-color:lightgray\">");
		out.println("<p> Forms will be reviewed for completeness and eligibility.  You will be notified if any additional information is needed. Mail completed formto <strong>Human Resources, 250 Columbus Place or fax to (617) 373-7610.</strong> All waivers must be received by HRM within 30 days of the course start date.");
		out.println("</p> </div>");
		out.println("<hr style=\"background-color:red;height: 2px; border:red\">");
		//out.println("<input type=\"submit\" style=\"padding:0.2rem 0.5rem; cursor:pointer; background-color:red; color:white; border:none\">");
		
		out.println("</body>");
		out.println("</html>");
	}
}